name: noor_e_quran
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:

  waveform_flutter: ^1.2.0
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  flutter_advanced_drawer: ^1.3.7
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  geocoding:
  location: ^7.0.1
  shared_preferences: ^2.3.5
  get_storage: ^2.1.1
  page_transition: ^2.2.1
  day_night_switch:
  glassmorphism_ui:
  google_nav_bar:
  line_icons:
  shimmer:
  quran:
  marquee:
  intl:
  flutter_svg:
  glowy_borders:
  audioplayers:
  share_plus:
  percent_indicator:
  islamic_hijri_calendar:
  hijri:
  animated_read_more_text:
  flutter_pdfview:
  table_calendar:
  vibration: ^3.1.3
  hadith:
  flutter_html:
  url_launcher:
  internet_connection_checker:
  simple_animation_progress_bar: ^1.8.2
  pdf:
  open_file: ^3.5.10
  printing:
  permission_handler:
  flutter_compass:
  flutter_map:
  latlong2:
  adhan:
  image_editor_plus:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/frames/
    - assets/json/
    - assets/pdf/
    - assets/audios/
    - assets/anim/
    - assets/editor/


  fonts:
    - family: grenda
      fonts:
        - asset: assets/fonts/grenda.ttf
          style: normal
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
          style: normal